const defaultEmailTemplates = (formLabel) => ({
    submitted: {
        enabled: "disabled",
        replyTo: "",
        subject: `${formLabel} Received - {{storeName}}`,
        body: `<p>Hi {{firstName}}</p><p>Thank you for your ${formLabel.toLowerCase()} to {{storeName}}.</p><p>We will review your submission and get back to you shortly.</p><p>Thank you<br/>{{storeName}}</p>`,
    },
    approved: {
        enabled: "disabled",
        replyTo: "",
        subject: `Your ${formLabel} has been Approved - {{storeName}}`,
        body: `<p>Hi {{firstName}}</p><p>Congratulations! Your ${formLabel.toLowerCase()} to {{storeName}} has been approved.</p><p>Thank you<br/>{{storeName}}</p>`,
    },
    rejected: {
        enabled: "disabled",
        replyTo: "",
        subject: `Update on your ${formLabel} - {{storeName}}`,
        body: `<p>Hi {{firstName}}</p><p>Thank you for your submission to {{storeName}}.</p><p>After reviewing your request, we are unable to proceed at this time.</p><p>Thank you<br/>{{storeName}}</p>`,
    },
    admin: {
        enabled: "disabled",
        replyTo: "",
        subject: `New ${formLabel} Received`,
        body: `<p>A new ${formLabel.toLowerCase()} has been received.</p><p>Please review the submission in your admin dashboard.</p>`,
    },
});

export const wholesaleFormConfig = {
    initialFields: [
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "website", label: "Company Website", type: "url", placeholder: "https://example.com", required: true, singletonType: "biz-website" },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "+91 81234 56789", required: false },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter last name", required: true },
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter first name", required: true },
        { id: "address", label: "Company Address", type: "text", placeholder: "Enter company address", required: true, singletonType: "biz-address" },
        { id: "businessType", label: "Type of Business", type: "text", placeholder: "e.g. Retailer, Distributor", required: true, singletonType: "biz-type" },
        { id: "taxId", label: "Tax ID/EIN", type: "text", placeholder: "Enter Tax ID", required: true, singletonType: "biz-tax-id" },
    ],
    defaultCategory: "b2b",
    formTitle: "Wholesale Application",
    formDescription: "Submit your information and we'll get back to you shortly.",
    pageHeading: "Wholesale form",
    formRole: "Wholesale Form",
    customerTag: "Wholesale",
    saveToastMessage: "Wholesale Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this wholesale form.",
    autoTagLabel: 'Auto-tag customer as "Wholesale"',
    emailTemplates: {
        submitted: {
            enabled: "disabled",
            replyTo: "",
            subject: "Wholesale Application Received - {{storeName}}",
            body: "<p>Hi {{firstName}}</p><p>Thank you for your wholesale application to {{storeName}}.</p><p>We will review your submitted details and share your application status shortly over email.</p><p>Thank you<br/>{{storeName}}</p>",
        },
        approved: {
            enabled: "disabled",
            replyTo: "",
            subject: "Your Wholesale Application has been Approved - {{storeName}}",
            body: "<p>Hi {{firstName}}</p><p>Congratulations! Your wholesale application to {{storeName}} has been approved.</p><p>Thank you<br/>{{storeName}}</p>",
        },
        rejected: {
            enabled: "disabled",
            replyTo: "",
            subject: "Update on your Wholesale Application - {{storeName}}",
            body: "<p>Hi {{firstName}}</p><p>Thank you for applying for a wholesale account with {{storeName}}.</p><p>After reviewing your application, we are unable to approve your request at this time.</p><p>Thank you<br/>{{storeName}}</p>",
        },
        admin: {
            enabled: "disabled",
            replyTo: "",
            subject: "New Wholesale Application Received",
            body: "<p>A new wholesale application has been received.</p><p>Please review the application in your admin dashboard.</p>",
        },
    },
};

export const contactFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone", type: "tel", placeholder: "+1 234 567 8900", required: false },
        { id: "subject", label: "Subject", type: "select", options: ["General Inquiry", "Support Request", "Billing Question", "Feedback"], placeholder: "Please select", required: false },
        { id: "message", label: "Message", type: "textarea", placeholder: "What can I help you?", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Contact Us",
    formDescription: "Send us a message and we'll respond as soon as possible.",
    pageHeading: "Contact form",
    formRole: "Contact Form",
    customerTag: "Contact",
    saveToastMessage: "Contact Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this contact form.",
    autoTagLabel: 'Auto-tag customer as "Contact"',
    emailTemplates: defaultEmailTemplates("Contact Form"),
};

export const retailerB2BFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "companyName", label: "Company Name", type: "text", placeholder: "Enter company name", required: true, singletonType: "biz-company-name" },
        { id: "companyEmail", label: "Business Email", type: "email", placeholder: "Enter business email", required: true, singletonType: "biz-company-email" },
        { id: "companyPhone", label: "Business Phone", type: "tel", placeholder: "Enter business phone", required: false, singletonType: "biz-company-phone" },
        { id: "companyAddress", label: "Company Address", type: "text", placeholder: "Enter company address", required: true, singletonType: "biz-address" },
    ],
    defaultCategory: "b2b",
    formTitle: "Retailer Application",
    formDescription: "Fill out the application below to register as an authorized retailer.",
    pageHeading: "Retailer form",
    formRole: "Retailer Form",
    customerTag: "Retailer",
    saveToastMessage: "Retailer Application Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this retailer form.",
    autoTagLabel: 'Auto-tag customer as "Retailer"',
    emailTemplates: defaultEmailTemplates("Retailer Application"),
};

export const retailerCustomFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "rating", label: "Overall Experience", type: "rating", placeholder: "", required: true },
        { id: "feedback", label: "Your Feedback", type: "textarea", placeholder: "Tell us about your experience...", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Customer Feedback",
    formDescription: "We value your opinion! Please share your experience with us.",
    pageHeading: "Feedback form",
    formRole: "Feedback Form",
    customerTag: "Feedback",
    saveToastMessage: "Feedback Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this feedback form.",
    autoTagLabel: 'Auto-tag customer as "Feedback"',
    emailTemplates: defaultEmailTemplates("Feedback Form"),
};

export const supplierB2BFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "companyName", label: "Company Name", type: "text", placeholder: "Enter company name", required: true, singletonType: "biz-company-name" },
        { id: "companyEmail", label: "Business Email", type: "email", placeholder: "Enter business email", required: true, singletonType: "biz-company-email" },
        { id: "companyAddress", label: "Company Address", type: "text", placeholder: "Enter company address", required: true, singletonType: "biz-address" },
        { id: "taxId", label: "Tax ID / EIN", type: "text", placeholder: "Enter Tax ID", required: true, singletonType: "biz-tax-id" },
        { id: "taxDoc", label: "Tax Documentation", type: "file", placeholder: "", required: false, singletonType: "biz-tax-doc" },
    ],
    defaultCategory: "b2b",
    formTitle: "Supplier Onboarding",
    formDescription: "Complete the onboarding questionnaire to register as an active supplier.",
    pageHeading: "Supplier form",
    formRole: "Supplier Form",
    customerTag: "Supplier",
    saveToastMessage: "Supplier Onboarding Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this supplier form.",
    autoTagLabel: 'Auto-tag customer as "Supplier"',
    emailTemplates: defaultEmailTemplates("Supplier Onboarding"),
};

export const supplierCustomFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "+1 234 567 8900", required: false },
        { id: "subject", label: "Subject", type: "text", placeholder: "E.g. Appointment Request / Return Inquiry", required: true },
        { id: "details", label: "Additional Details", type: "textarea", placeholder: "Please provide full details here...", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "General Request Form",
    formDescription: "Submit your request details and a representative will follow up soon.",
    pageHeading: "Request form",
    formRole: "Request Form",
    customerTag: "Request",
    saveToastMessage: "Request Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this request form.",
    autoTagLabel: 'Auto-tag customer as "Request"',
    emailTemplates: defaultEmailTemplates("Request Form"),
};

export const scratchFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "Enter your phone number", required: false },
    ],
    defaultCategory: "custom",
    formTitle: "Custom Form",
    formDescription: "Fill out the custom form below.",
    pageHeading: "Custom form",
    formRole: "Custom Form",
    customerTag: "Custom",
    saveToastMessage: "Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this form.",
    autoTagLabel: 'Auto-tag customer as "Custom"',
    emailTemplates: defaultEmailTemplates("Custom Form"),
};

export const productInquiryFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "Enter your phone number", required: false },
        { id: "productName", label: "Product Name / SKU", type: "text", placeholder: "Enter product details", required: true },
        { id: "inquiryDetails", label: "Inquiry Details", type: "textarea", placeholder: "What would you like to know about this product?", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Product Inquiry",
    formDescription: "Ask us anything about our products and we'll get back to you shortly.",
    pageHeading: "Product Inquiry",
    formRole: "Product Inquiry Form",
    customerTag: "Inquiry",
    saveToastMessage: "Product Inquiry Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this product inquiry form.",
    autoTagLabel: 'Auto-tag customer as "Inquiry"',
    emailTemplates: defaultEmailTemplates("Product Inquiry"),
};

export const returnRefundFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "orderId", label: "Order Number", type: "text", placeholder: "e.g. #1001", required: true },
        { id: "reason", label: "Reason for Return", type: "select", options: ["Damaged on Arrival", "Wrong Size/Color", "Product Defect", "Other"], placeholder: "Select reason", required: true },
        { id: "details", label: "Additional Information", type: "textarea", placeholder: "Please explain your return request...", required: false },
    ],
    defaultCategory: "custom",
    formTitle: "Return & Refund Request",
    formDescription: "Submit your return request and our team will review it within 24 hours.",
    pageHeading: "Return form",
    formRole: "Return Form",
    customerTag: "Return",
    saveToastMessage: "Return Form saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this return form.",
    autoTagLabel: 'Auto-tag customer as "Return"',
    emailTemplates: defaultEmailTemplates("Return Request"),
};

export const warrantyRegistrationFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "Enter your phone number", required: false },
        { id: "serialNumber", label: "Product Serial Number", type: "text", placeholder: "e.g. SN-123456", required: true },
        { id: "purchaseDate", label: "Date of Purchase", type: "text", placeholder: "YYYY-MM-DD", required: true },
        { id: "purchasePlace", label: "Retailer / Place of Purchase", type: "text", placeholder: "Where did you buy it?", required: false },
    ],
    defaultCategory: "custom",
    formTitle: "Warranty Registration",
    formDescription: "Register your product warranty online to secure your warranty coverage.",
    pageHeading: "Warranty form",
    formRole: "Warranty Form",
    customerTag: "Warranty",
    saveToastMessage: "Warranty Registration saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this warranty form.",
    autoTagLabel: 'Auto-tag customer as "Warranty"',
    emailTemplates: defaultEmailTemplates("Warranty Registration"),
};

export const appointmentBookingFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "phone", label: "Phone Number", type: "tel", placeholder: "Enter your phone number", required: true },
        { id: "bookingDate", label: "Preferred Date & Time", type: "text", placeholder: "e.g. Oct 12, 10:00 AM", required: true },
        { id: "serviceType", label: "Service Needed", type: "select", options: ["Initial Consultation", "Technical Support", "Bespoke Design Setup"], placeholder: "Select service", required: true },
        { id: "notes", label: "Special Instructions / Notes", type: "textarea", placeholder: "Tell us more about your request...", required: false },
    ],
    defaultCategory: "custom",
    formTitle: "Schedule Appointment",
    formDescription: "Book a slot with one of our specialized representatives.",
    pageHeading: "Booking form",
    formRole: "Booking Form",
    customerTag: "Booking",
    saveToastMessage: "Appointment Request submitted successfully!",
    mailDescription: "Configure automatic emails sent when users submit this booking form.",
    autoTagLabel: 'Auto-tag customer as "Booking"',
    emailTemplates: defaultEmailTemplates("Appointment Booking"),
};

export const eventRegistrationFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email", type: "email", placeholder: "Enter your email", required: true },
        { id: "guests", label: "Number of Guests", type: "select", options: ["Just Me", "1 Guest", "2 Guests", "3+ Guests"], placeholder: "Select", required: true },
        { id: "dietary", label: "Dietary Restrictions", type: "select", options: ["None", "Vegetarian", "Vegan", "Gluten-Free", "Other"], placeholder: "Select option", required: false },
        { id: "attending", label: "Will you attend?", type: "select", options: ["Yes, I will be there!", "No, I cannot attend", "Maybe"], placeholder: "Select RSVP", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Event RSVP & Registration",
    formDescription: "Register your spot for our upcoming brand event and let us know your RSVP details.",
    pageHeading: "RSVP form",
    formRole: "RSVP Form",
    customerTag: "RSVP",
    saveToastMessage: "RSVP Registration saved successfully!",
    mailDescription: "Configure automatic emails sent when users submit this RSVP form.",
    autoTagLabel: 'Auto-tag customer as "RSVP"',
    emailTemplates: defaultEmailTemplates("Event RSVP"),
};

export const newsletterSignupFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true },
        { id: "email", label: "Email Address", type: "email", placeholder: "Enter your best email", required: true },
        { id: "interests", label: "Interests", type: "select", options: ["All Updates", "New Product Launches", "Exclusive Wholesale Deals"], placeholder: "Select your main interest", required: false },
    ],
    defaultCategory: "custom",
    formTitle: "Newsletter Signup",
    formDescription: "Subscribe to stay updated with product launches, updates, and special promotions.",
    pageHeading: "Newsletter form",
    formRole: "Newsletter Form",
    customerTag: "Newsletter",
    saveToastMessage: "Newsletter subscription saved successfully!",
    mailDescription: "Configure automatic emails sent when users subscribe.",
    autoTagLabel: 'Auto-tag customer as "Newsletter"',
    emailTemplates: defaultEmailTemplates("Newsletter"),
};

export const supportTicketFormConfig = {
    initialFields: [
        { id: "firstName", label: "Your Name", type: "text", placeholder: "Enter your name", required: true },
        { id: "email", label: "Email Address", type: "email", placeholder: "Enter your email address", required: true },
        { id: "priority", label: "Priority Level", type: "select", options: ["Low", "Medium", "High", "Critical"], placeholder: "Select priority", required: true },
        { id: "ticketCategory", label: "Issue Category", type: "select", options: ["Billing & Payments", "Shipping & Delivery", "Technical Issue", "Account Management"], placeholder: "Select category", required: true },
        { id: "description", label: "Description of the issue", type: "textarea", placeholder: "Describe your query in full detail...", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Support Ticket",
    formDescription: "Open a support request and our support desk will respond shortly.",
    pageHeading: "Support Ticket",
    formRole: "Support Ticket Form",
    customerTag: "Support",
    saveToastMessage: "Support Ticket submitted successfully!",
    mailDescription: "Configure automatic emails sent when support tickets are raised.",
    autoTagLabel: 'Auto-tag customer as "Support"',
    emailTemplates: defaultEmailTemplates("Support Ticket"),
};

export const surveyFormConfig = {
    initialFields: [
        { id: "firstName", label: "Full Name (Optional)", type: "text", placeholder: "Enter your name", required: false },
        { id: "email", label: "Email Address (Optional)", type: "email", placeholder: "Enter your email", required: false },
        { id: "rating", label: "Overall Satisfaction", type: "rating", placeholder: "", required: true },
        { id: "source", label: "How did you hear about us?", type: "select", options: ["Google / Search Engine", "Social Media", "Friend Referral", "Other"], placeholder: "Select option", required: false },
        { id: "comments", label: "Any recommendations for us?", type: "textarea", placeholder: "We would love to hear your suggestions...", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Customer Satisfaction Survey",
    formDescription: "Help us serve you better by taking 2 minutes to fill out this survey.",
    pageHeading: "Survey Form",
    formRole: "Survey Form",
    customerTag: "Survey",
    saveToastMessage: "Survey Response saved successfully!",
    mailDescription: "Configure automatic emails sent when surveys are completed.",
    autoTagLabel: 'Auto-tag customer as "Survey"',
    emailTemplates: defaultEmailTemplates("Survey"),
};

export const membershipSignupFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email Address", type: "email", placeholder: "Enter email", required: true },
        { id: "birthDate", label: "Date of Birth", type: "text", placeholder: "YYYY-MM-DD", required: false },
        { id: "tier", label: "Membership Tier", type: "select", options: ["Silver Member (Free)", "Gold Member ($10/mo)", "Platinum VIP ($25/mo)"], placeholder: "Select Tier", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "VIP Club Membership",
    formDescription: "Register below to unlock exclusive discounts, early access, and members-only updates.",
    pageHeading: "Membership form",
    formRole: "Membership Form",
    customerTag: "Member",
    saveToastMessage: "Membership Registration saved successfully!",
    mailDescription: "Configure automatic emails sent when users join.",
    autoTagLabel: 'Auto-tag customer as "Member"',
    emailTemplates: defaultEmailTemplates("Membership Registration"),
};

export const customOrderRequestFormConfig = {
    initialFields: [
        { id: "firstName", label: "First Name", type: "text", placeholder: "Enter your first name", required: true, columnWidth: "50%" },
        { id: "lastName", label: "Last Name", type: "text", placeholder: "Enter your last name", required: true, columnWidth: "50%" },
        { id: "email", label: "Email Address", type: "email", placeholder: "Enter your email", required: true },
        { id: "budget", label: "Estimated Budget ($)", type: "text", placeholder: "e.g. $500 - $1000", required: false },
        { id: "specs", label: "Bespoke Specifications", type: "textarea", placeholder: "Describe size, materials, colors, and instructions...", required: true },
    ],
    defaultCategory: "custom",
    formTitle: "Bespoke Custom Order",
    formDescription: "Submit details of your custom fabrication request and get a quote.",
    pageHeading: "Custom order form",
    formRole: "Custom Order Form",
    customerTag: "CustomOrder",
    saveToastMessage: "Bespoke Order Request saved successfully!",
    mailDescription: "Configure automatic emails sent when custom order inquiries are sent.",
    autoTagLabel: 'Auto-tag customer as "CustomOrder"',
    emailTemplates: defaultEmailTemplates("Custom Order"),
};
